# ==============================================================================
# Monowm Core Configuration (config.conf)
# ==============================================================================

# Maximum number of windows that can be open at the same time (max 128)
max_windows = 9

# Internal Window Manager Keybindings
# Format: modifiers+keysym (modifiers can be: super, shift, control, alt)
bind_quit = super+q
bind_cycle = super+Tab
cycle_enabled = 0
bind_switch_window_mod = super+Shift
bind_reload = control+F4
bind_toggle_bar = control+F5

# Autostart Commands (run when monowm starts)
run = dunst
run = feh --bg-fill ~/.config/monowm/bg.png
run =  alttab -w 1 -mk Super_L -t 224x256 -i 64x64 -font 'xft:sans-20' -bg '#303446' -fg '#c6d0f5' -frame '#babbf1' -inact '#737994' -bc '#292c3c'
run = dbus-update-activation-environment --systemd --all

# Custom Hotkeys (replaces sxhkd)
# Format: keybind = modifiers+keysym : command
keybind = super+Return : alacritty
keybind = super+space : dmenu_run -fn 'monospace-14' -nb '#303446' -nf '#c6d0f5' -sb '#babbf1' -sf '#292c3c'
keybind = super+b : chromium
keybind = XF86AudioRaiseVolume : ~/.local/bin/monowm-volume up
keybind = XF86AudioLowerVolume : ~/.local/bin/monowm-volume down
keybind = XF86AudioMute : ~/.local/bin/monowm-volume mute
keybind = XF86AudioMicMute : wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
keybind = XF86MonBrightnessUp : ~/.local/bin/monowm-brightness upc
keybind = XF86MonBrightnessDown : ~/.local/bin/monowm-brightness down
