# ==============================================================================
# Monowm Core Configuration (config.conf)
# ==============================================================================

# Maximum number of windows that can be open at the same time (max 128)
max_windows = 9

# Internal Window Manager Keybindings
# Format: modifiers+keysym (modifiers can be: super, shift, control, alt)
bind_quit = super+q
bind_window_switcher = super+Tab
bind_cycle_forward = super+j
bind_cycle_back = super+k

#the prefix for switching using mod 1-9
bind_switch_window_mod = super+Shift

bind_reload = control+F4
bind_toggle_bar = control+F5

# Autostart Commands (run when monowm starts)
run = dunst
run = xcompmgr -n
run = xwallpaper --zoom ~/.config/monowm/bg.png
run = dbus-update-activation-environment --systemd --all

# Custom Hotkeys (replaces sxhkd)
# Format: keybind = modifiers+keysym : command
keybind = super+Return : alacritty
keybind = super+space : dmenu_run -fn 'monospace-14' -nb '#303446' -nf '#c6d0f5' -sb '#babbf1' -sf '#292c3c'
keybind = super+b : chromium
keybind = XF86AudioRaiseVolume : monowm-volume up
keybind = XF86AudioLowerVolume : monowm-volume down
keybind = XF86AudioMute : monowm-volume mute
keybind = XF86AudioMicMute : wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
keybind = XF86MonBrightnessUp : monowm-brightness up
keybind = XF86MonBrightnessDown : monowm-brightness down
