# ==============================================================================
# Monowm Core Configuration (config.conf)
# ==============================================================================

# Maximum number of windows that can be open at the same time (max 128)
max_windows = 9

#reload monowm, use after making changes to conf
bind_reload = control+F4

# Internal Window Manager Keybindings
# Format: modifiers+keysym (modifiers can be: super, shift, control, alt)
bind_quit = super+q
bind_cycle_forward = super+j
bind_cycle_back = super+k
bind_mru_switcher = super+Tab

#the prefix for switching using mod 1-9
bind_switch_window_mod = super+Shift

# Format: keybind = modifiers+keysym : command
keybind = super+Return : alacritty
keybind = super+space : rofi -show drun -theme purple -font "monospace 28"
keybind = super+b : chromium
keybind = XF86AudioRaiseVolume : monowm-volume up
keybind = XF86AudioLowerVolume : monowm-volume down
keybind = XF86AudioMute : monowm-volume mute
keybind = XF86AudioMicMute : wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
keybind = XF86MonBrightnessUp : monowm-brightness up
keybind = XF86MonBrightnessDown : monowm-brightness down
